### ISSUE TITLE
py2和py3的安装区别

### ISSUE THREAD

**Issue by eeeeeeeeeeeeeeeea** [IZAY01/LibcSearcher#1]
py2可以用这种方法安装嘛

**Comment by zarkivy** [comment]
没有主动兼容py2，也未在py2上进行测试。同时也仅上传到了py3的pypi。

**Comment by xunruo** [comment]
可以试试

**Comment by wzsx150** [comment]
> 没有主动兼容py2，也未在py2上进行测试。同时也仅上传到了py3的pypi。

我试了一下，py2.7.18,安装会报错。能不能麻烦大佬也适配一下py2，毕竟还有很多人在用py2写pwn，需要修改的地方应该不多。
