### ISSUE TITLE
考虑以后添加查询one_gadget查询支持吗？

### ISSUE THREAD

**Issue by PikaCat-OuO** [IZAY01/LibcSearcher#3]
例如：
libc = LibcSearcher('fgets', 0x7ff39014bd90)
libc_base = 0x7ff39014bd90 - libc.dump('fgets')
one_gadget_address = libc_base + libc.one_gadget()  # 这里弹出一个像选择libc一样的东西让用户选择使用哪一个one_gadget

**Comment by zarkivy** [comment]
one_gadget 是 ruby 写的。对接的实现成本和必要性感觉都不太合适耶……

**Comment by PikaCat-OuO** [comment]
> one_gadget 是 ruby 写的。对接的实现成本和必要性感觉都不太合适耶……

其实有现成的可用代码：https://pypi.org/project/pwnscripts/
可以参考里面的`libc() provides one_gadget integration in the form of an interactive selection:`
还有这个：https://pypi.org/project/one-gadget/

**Comment by PikaCatPlusPlus** [comment]
> one_gadget 是 ruby 写的。对接的实现成本和必要性感觉都不太合适耶……

其实有现成的可用代码：https://pypi.org/project/pwnscripts/，可以参考里面的`libc() provides one_gadget integration in the form of an interactive selection:`

**Comment by zarkivy** [comment]
看了一下它们的实现，加上one_gadget的话会增添不少依赖。本身LibcSearcher的功能实现只是一个小脚本，加上这些大的包依赖却只是为了一个小小的接口调用，感觉本末倒置……
LibcSearcher就只用来 search libc 就行。并没有帮忙安装其它库，并调用它们中的功能的必要性……
