### ISSUE TITLE
libcsearcher似乎不太好用了

### ISSUE THREAD

**Issue by chenjunhub** [IZAY01/LibcSearcher#7]
我使用了redame中的实例代码，得出的libc版本为2.13，但是我实际的版本为2.31。（GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.8) stable release version 2.31.）

**Comment by zarkivy** [comment]
我这里测试并没有出现该现象，我需要你那边更为详细的错误信息。可以复制你测试用的代码、命令或相关截图吗？
